version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: locadora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: back-end
    container_name: back-end
    depends_on:
      - db
    ports:
      - "8040:8040"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/locadora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    image: front-end
    container_name: front-end
    depends_on:
      - app
    ports:
      - "8081:8080"

volumes:
  postgres_data:
